### ISSUE TITLE
Parameter 'from' should have a numerical value equal or larger than 1. 

### ISSUE THREAD

**Issue by erikarasnick** [geomarker-io/addNlcdData#3]
https://github.com/geomarker-io/addNlcdData/blob/e246a858c88e7336e9d374a74fa3faea74cb2e79/R/nlcd_data_functions.R#L54

If the nlcd cell number is xxx0000000, the 'from' argument in read_fst is 0, causing the above error.

**Comment by cole-brokamp** [comment]
Looking into this lead me to discovering an error over in the nlcd_raster_to_fst repository with the chunk and row number to nlcd_call number mapping.  This is currently causing the cell numbers retrieved to be off by 1 from the desired cell in this package too.  I'm closing this over here for now, because I think its going to require a re-do of the dataset.  I'll track the progress on that issue you originally opened (https://github.com/geomarker-io/nlcd_raster_to_fst/issues/1) and report back here when I solve it.
